apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-nfs
  namespace: default
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html/   # pod中挂载的路径
  volumes:
  - name: html
    nfs:
      path: /data/volumes   # nfs 服务端共享的目录
      server: nfs.k8s.com   # 使用域名的方式，在节点添加hosts文件映射到nfs服务端ip即可

