apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-hostpath
  namespace: default
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    volumeMounts:     # 将宿主机的共享文件或者目录挂载至容器位置
    - name: html
      mountPath: /usr/share/nginx/html/
  volumes:            # 创建存储卷
  - name: html        # 存储卷名字，必须定义
    hostPath:
      path: /data/pod/volumel
      type: DirectoryOrCreate    # 挂载类型为目录不存在则自动创建
