apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001 #注意，定义pv时一定不要加名称空间；因为pv时属于整个集群的，而不是属于某个名称空间，但是pvc时属于某个名称空间的
  labels:
    name: pv001
spec:
  accessModes: ["ReadWriteMany","ReadWriteOnce"] #多人读写，一人读写，简称RWX，RWO
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  capacity: #分配磁盘空间大小
    storage: 4Gi
  nfs:
    path: /data/volumes/v1
    server: nfs.k8s.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
  labels:
    name: pv002
spec:
  accessModes: ["ReadWriteOnce"] #一人读写
  capacity:
    storage: 2Gi
  nfs:
    path: /data/volumes/v2
    server: nfs.k8s.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv003
  labels:
    name: pv003
spec:
  accessModes: ["ReadOnlyMany","ReadWriteOnce"] #多人只读，一人读写
  capacity:
    storage: 1Gi
  nfs:
    path: /data/volumes/v3
    server: nfs.k8s.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv004
  labels:
    name: pv004
spec:
  accessModes: ["ReadOnlyMany"] #多人只读，ROX
  capacity:
    storage: 1Gi
  nfs:
    path: /data/volumes/v4
    server: nfs.k8s.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv005
  labels:
    name: pv005
spec:
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  capacity:
    storage: 3Gi
  nfs:
    path: /data/volumes/v5
    server: nfs.k8s.com

