apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001 #注意，定义pv时一定不要加名称空间；因为pv时属于整个集群的，而不是属于某个名称空间，但是pvc时属于某个名称空间的
  labels:
    name: pv001
spec:
  nfs:
    path: /data/volumes/v1
    server: k8s-node2.com
  accessModes: ["ReadWriteMany","ReadWriteOnce"] #多人读写，一人读写，简称RWX，RWO
  capacity: #分配磁盘空间大小
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002 #注意，定义pv时一定不要加名称空间；因为pv时属于整个集群的，而不是属于某个名称空间，但是pvc时属于某个名称空间的
  labels:
    name: pv002
spec:
  nfs:
    path: /data/volumes/v2
    server: k8s-node2.com
  accessModes: ["ReadWriteOnce"] #一人读写
  capacity: #分配磁盘空间大小
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv003 #注意，定义pv时一定不要加名称空间；因为pv时属于整个集群的，而不是属于某个名称空间，但是pvc时属于某个名称空间的
  labels:
    name: pv003
spec:
  nfs:
    path: /data/volumes/v3
    server: k8s-node2.com
  accessModes: ["ReadOnlyMany","ReadWriteOnce"] #多人只读，一人读写
  capacity: #分配磁盘空间大小
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv004 #注意，定义pv时一定不要加名称空间；因为pv时属于整个集群的，而不是属于某个名称空间，但是pvc时属于某个名称空间的
  labels:
    name: pv004
spec:
  nfs:
    path: /data/volumes/v4
    server: k8s-node2.com
  accessModes: ["ReadOnlyMany"] #多人只读，ROX
  capacity: #分配磁盘空间大小
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv005 #注意，定义pv时一定不要加名称空间；因为pv时属于整个集群的，而不是属于某个名称空间，但是pvc时属于某个名称空间的
  labels:
    name: pv005
spec:
  nfs:
    path: /data/volumes/v5
    server: k8s-node2.com
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  capacity: #分配磁盘空间大小
    storage: 1Gi

