apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness-tcp
    app: goproxy
  name: liveness-tcp
spec:
  containers:
  - name: goproxy
    image: docker.io/googlecontainer/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe: # 就绪性探针
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5  # 容器启动之后多长时间开始探测，默认是容器已启动开始探测。
      periodSeconds: 10       # 执行探测的频率(以秒为单位)。默认为10秒。最低值是1
      failureThreshold: 3     # 探测几次失败 才认为失败,默认为3。最小值为1。
      timeoutSeconds: 1       # 探针超时的秒数。默认值是1秒。最小值为1。
      successThreshold: 1     # 从上次检查失败后重新认定检查成功的检查次数阈值（必须是连续成功），默认为1
    livenessProbe: # 存活性探针
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
