apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-tcp-nginx
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: liveness-tcp-nginx
  template: #pod模板
    metadata:
      labels:
        app: liveness-tcp-nginx
      name: liveness-tcp-nginx
    spec:
      containers:
      - name: redis
        image: registry.cn-shanghai.aliyuncs.com/outsrkem/nginx:1.15.2-tools
        imagePullPolicy: IfNotPresent
        resources: #资源管理
          requests: #容器运行时，最低资源需求
            cpu: 100m # #CPU资源（核数），两种方式，浮点数或者是整数+m，0.1=100m，最少值为0.001核（1m）
            memory: 10Mi
          limits: #资源限制
            cpu: 200m
            memory: 20Mi
        ports:
        - containerPort: 80       # containerPort是pod内部容器的端口，targetPort映射到containerPort。
          name: httpd
          protocol: TCP
        readinessProbe: # 就绪性探针
          tcpSocket:
            port: 80
          initialDelaySeconds: 1  # 容器启动之后多长时间开始探测，默认是容器已启动开始探测。
          periodSeconds: 10       # 执行探测的频率(以秒为单位)。默认为10秒。最低值是1
          failureThreshold: 3     # 探测几次失败 才认为失败,默认为3。最小值为1。
          timeoutSeconds: 1       # 探针超时的秒数。默认值是1秒。最小值为1。
          successThreshold: 1     # 从上次检查失败后重新认定检查成功的检查次数阈值（必须是连续成功），默认为1
        livenessProbe: # 存活性探针
          tcpSocket:
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 20
          failureThreshold: 3
          timeoutSeconds: 1
          successThreshold: 1
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.96.0.10
        searches:
          - nginx.svc.cluster.local
        options:
          - name: single-request-reopen          
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: liveness-tcp-nginx
  ports:
  - port: 80
    targetPort: 80
