apiVersion: v1
kind: Service
metadata:
  name: myapp-headless
  namespace: default
spec:
  selector:
    app: myapp
    release: canary
  clusterIP: None # 此处为None，则创建的svc是没有IP的
  ports:
  - port: 80
    targetPort: 80
# 无头svc
