apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    app: myapp
    release: canary
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080

---
# sessionAffinity: ClientIP  # 定义sessionAffinity ，此时注释掉，下面是用补丁方式
# # kubectl patch svc myapp -p '{"spec":{"sessionAffinity":"None"}}'
# # kubectl patch svc myapp -p '{"spec":{"externalTrafficPolicy":"Local"}}'
# # nodePor 只有type: NodePort 时 才 能 生 效
