apiVersion: v1 
kind: Pod
metadata:
  name: pod-demo-test
  namespace: default
  labels:
    # kv格式的，也可以用花括号表示
    app: myapp
    # 定义所属的层次
    tier: frontend
  # 资源注解,与label不同的地方在于，他不能用于挑选资源对象，仅仅用于为对象提供“元数据”
  annotations:
    magedu.com/created-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports: 
    - name: http
      containerPort: 80
    - name: https
      containerPort: 443 
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command:
    # command: [ "/bin/sh","-c","sleep 3600" ]
    - "/bin/sh"
    - "-c"
    - "sleep 3600"
  nodeSelector:
    disktype: ssd
