# 重启pod
# kubectl rollout restart deployment myapp-deploy
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lb-nginx-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: lb-nginx
      roles: apiserver-lb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lb-nginx
        roles: apiserver-lb
    spec:
      hostNetwork: true
      containers:
      - name: lb-nginx
        image: registry.cn-shanghai.aliyuncs.com/outsrkem/nginx:1.15.2-lb
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5443
          protocol: TCP
        volumeMounts:
        - name: vol-lb-nginx-conf
          mountPath: /usr/local/nginx/conf.d/lb-nginx.conf
          subPath: lb-nginx.conf
          readOnly: true
        - name: vol-lb-nginx-logs
          mountPath: /usr/local/nginx/logs
        livenessProbe:
          tcpSocket:
            port: 5443
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 3
          timeoutSeconds: 1
          successThreshold: 1
        readinessProbe:
          tcpSocket:
            port: 5443
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 3
          timeoutSeconds: 1
          successThreshold: 1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      nodeSelector:
        kubernetes.io/halb: apiserver-lb
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 998
        seLinuxOptions: {}
      volumes:
      - name: vol-lb-nginx-conf
        configMap:
          defaultMode: 288
          items:
            - key: lb-nginx.conf
              path: lb-nginx.conf
          name: lb-nginx-conf
      - name: vol-lb-nginx-logs
        hostPath:
          path: /var/log/nginx
          type: DirectoryOrCreate
      dnsPolicy: ClusterFirstWithHostNet
      hostAliases:
        - hostnames:
          - master-01.master.kubernetes
          - master-02.master.kubernetes
          ip: 10.10.10.31
        - hostnames:
          - www.baidu.com
          ip: 36.152.44.96
      dnsConfig:
        nameservers:
          - 192.168.88.2  # 配置集群外节点dns(可选)
        options:
          - name: timeout
            value: ''
          - name: ndots
            value: '5'
          - name: single-request-reopen

---
apiVersion: v1
kind: Service
metadata:
  name: lb-nginx
  namespace: kube-system
spec:
  clusterIP: 
  ports:
  - port: 5443
    protocol: TCP
    targetPort: 5443
  selector:
    app: lb-nginx
    roles: apiserver-lb
  sessionAffinity: None
  type: ClusterIP



