apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lb-nginx-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: lb-nginx
      roles: apiserver-lb
  template:
    metadata:
      labels:
        app: lb-nginx
        roles: apiserver-lb
    spec:
      hostNetwork: true
      containers:
      - name: lb-nginx
        image: registry.cn-shanghai.aliyuncs.com/outsrkem/nginx:1.15.2-lb
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5443
          protocol: TCP
        volumeMounts:
        - name: vol-lb-nginx-conf
          mountPath: /usr/local/nginx/conf.d/lb-nginx.conf
          subPath: lb-nginx.conf
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 5443
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 3
          timeoutSeconds: 1
          successThreshold: 1
        readinessProbe:
          tcpSocket:
            port: 5443
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 3
          timeoutSeconds: 1
          successThreshold: 1
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      nodeSelector:
        kubernetes.io/halb: apiserver-lb
      securityContext:
        fsGroup: 998        
      volumes:
      - name: vol-lb-nginx-conf
        configMap:
          defaultMode: 288
          name: lb-nginx-conf

---
apiVersion: v1
kind: Service
metadata:
  name: lb-nginx
  namespace: kube-system
spec:
  selector:
      app: lb-nginx
      roles: apiserver-lb
  sessionAffinity: None
  ports:
  - protocol: TCP
    port: 5443
    targetPort: 5443


