apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec-pod
  namespace: default
spec:
  containers:
  - name: liveness-exec-container
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c","touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 3600"]
    livenessProbe: #存活性探针
        exec: #探针方式（执行用户定义的命令方式）
           command: ["test","-e","/tmp/healthy"] #-e 判断文件是否存在
        initialDelaySeconds: 1 #表示容器启动后1s后开始探测
        periodSeconds: 3 #表示每3s探测一次

