apiVersion: v1
kind: Secret
metadata:
  name: mysecret  # secret资源的名字
type: Opaque
data:   # base64编码
  username: YWRtaW4=   # admin
  password: MWYyZDFlMmU2N2Rm  # 1f2d1e2e67df
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy-secret
  namespace: default
spec: #这里是指的是控制器的spec
  replicas: 2 # 副本个数
  selector:   #标签选择器
    matchLabels:
      app: myapp
      release: canary
      name: secret
  template: #pod模板
    metadata:
      labels: #要跟标签选择器是一样的
        app: myapp
        release: canary
        name: secret
    spec: #这里是pod的spec
      containers:
      - name: myapp-secret
        image: ikubernetes/myapp:v2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: foo # 使用secret的名字挂载
            mountPath: "/opt/mysecret"
            readOnly: true
        ports:
          - name: http
            containerPort: 80
      volumes:
        - name: foo # 指定secret的名字
          secret:
            secretName: mysecret  # secret资源的名字

