apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy-secret
  namespace: default
spec: #这里是指的是控制器的spec
  replicas: 2 #几个副本
  selector:   #标签选择器
    matchLabels: #攥着键值对模式
      app: myapp
      release: canary
      name: secret
  template: #pod模板
    metadata:
      labels: #要跟标签选择器是一样的
        app: myapp
        release: canary
        name: secret
    spec: #这里是pod的spec
      containers:
      - name: myapp-secret
        image: ikubernetes/myapp:v2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: foo
            mountPath: "/opt/mysecret"
            readOnly: true
            defaultMode: 256
        ports:
          - name: http
            containerPort: 80
      volumes:
        - name: foo
          secret:
            secretName: mysecret


