apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.10.10.31  # 本机ip
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: master-01.k8s.io
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  certSANs:    # 这里要写所有master主机名和ip以及虚拟ip和必要的DNS
  - "kubernetes"
  - "kubernetes.default"
  - "kubernetes.default.svc"
  - "kubernetes.default.svc.cluster.local"
  - "10.96.0.1"
  - "127.0.0.1"
  - "10.10.10.100"  # VIP
  - "10.10.10.31"   # master-01的ip
  - "10.10.10.32"   # master-02的ip
  - "10.10.10.33"   # master-03的ip
  - "localhost"
  - "localhost.localdomain"
  - "apiserver.cluster.kubernetes"  # VIP的hosts映射(域名)，可选
  - "master-01.k8s.io"    # master-01的主机名
  - "master-02.k8s.io"    # master-02的主机名
  - "master-03.k8s.io"    # master-03的主机名
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
# controlPlaneEndpoint: 虚拟ip(10.10.10.100:5443)或者域名apiserver.cluster.kubernetes:5443均可.
# 建议写域名，更换vip更方便
controlPlaneEndpoint: 10.10.10.100:5443
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  external: # 外部etcd，需要自行部署
    endpoints:
    - https://10.10.10.31:2379
    - https://10.10.10.32:2379
    - https://10.10.10.33:2379
    caFile: /opt/kubernetes/ssl/ca.pem
    certFile: /opt/kubernetes/ssl/etcd.pem
    keyFile: /opt/kubernetes/ssl/etcd-key.pem

imageRepository: registry.aliyuncs.com/google_containers
kind: ClusterConfiguration
kubernetesVersion: v1.16.2
networking:
  dnsDomain: cluster.local
  podSubnet: "10.244.0.0/16"
  serviceSubnet: 10.96.0.0/12
scheduler: {}
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: "rr"
  strictARP: false
  syncPeriod: 30s




# 添加master节点
# 1. 复制master节点/etc/kubernetes/pki 证书到另一台master节点，执行下面命令添加即可
# 2. 问题：加入后使用get pods -o wide 显示的ip是另一个网卡的(配置主机名解析后正常)
# 3. kubeadm config print join-defaults --component-configs KubeProxyConfiguration KubeletConfiguration (未验证)
# 4. --apiserver-advertise-address 指定节点的ip，默认会使用一个有网关的ip
kubeadm join 10.10.10.100:5443 --token abcdef.0123456789abcdef \
--discovery-token-ca-cert-hash sha256:7a7f4e98a080ef0279cbd3519f01b0732aa76d6694a318be077348a29d469fe3 \
--control-plane --apiserver-advertise-address 10.10.10.32
