apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
    name: pv001
spec:
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 2Gi
  nfs:
    path: /data/volumes/v1
    server: nfs.k8s.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
  labels:
    name: pv002
spec:
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 2Gi
  nfs:
    path: /data/volumes/v2
    server: nfs.k8s.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv003
  labels:
    name: pv003
spec:
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 2Gi
  nfs:
    path: /data/volumes/v3
    server: nfs.k8s.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv004
  labels:
    name: pv004
spec:
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 2Gi
  nfs:
    path: /data/volumes/v4
    server: nfs.k8s.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv005
  labels:
    name: pv005
spec:
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 2Gi
  nfs:
    path: /data/volumes/v5
    server: nfs.k8s.com

