apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-1
  namespace: default
  labels:
    app: myapp
    tier: frontend
  annotations:
    yong.com/created-by: "cluster-admin" #这是注解的键值对
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    env: #这是一个容器的属性
    - name: MYSQL_ROOT_PASSWORD
      valueFrom: #kubectl explain pods.spec.containers.env.valueFrom
        secretKeyRef: #表示我们要引用一个configmap来获取数据
          name: mysql-root-password #这是configmap的名字，也就是通过kubectl get cm获取的名字
          key: password #通过kubectl describe cm nginx-config的键
    #定义第二个环境变量
    #- name: NGINX_SERVER_NAME
    #  valueFrom: #kubectl explain pods.spec.containers.env.valueFrom
    #    configMapKeyRef:
    #      name: nginx-config
    #      key: server_name
